spring.application.name=aiFitness

# Server Configuration
server.port=8082
#Mongodb Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/AiServiceFitness
logging.level.org.springframework.data.mongodb.core=DEBUG


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
