spring.application.name=activityService
eureka.instance.prefer-ip-address=true

#connect with MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/AiActivityFitness
server.port=8081
logging.level.org.springframework.data.mongodb.core=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
