eureka.instance.prefer-ip-address=true

#connect with MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=aiActivityFitness
server.port=8081
logging.level.org.springframework.data.mongodb.core=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic.name=activity-events